apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: github-tests-dotnet-basic-cffacjia
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-tests-dotnet-basic-cffacjia 
  name: github-tests-dotnet-basic-cffacjia
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: github-tests-dotnet-basic-cffacjia 
